comhub/file_sharing_app/urls.py
from django.urls import path
from . import views as file_sharing_views

urlpatterns = [
    path("", file_sharing_views.home, name="home"),
    path("about/", file_sharing_views.about, name="about"),
    path("users_/<str:username>/", file_sharing_views.update_user, name="update_user"),
    path("customer_file_page/<str:username>/", file_sharing_views.customer_file_page, name="customer_file_page"),
    path("customer_file_upload_page/<str:username>/<int:file_id>/", file_sharing_views.customer_file_upload_page, name="customer_file_upload_page"),
    path("delete_file/<int:file_id>/", file_sharing_views.delete_file, name="delete_file"),
    
]

comhub/users/urls.py
from django.urls import path

from comhub.users.views import (
    delete_user,
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("<str:username>/delete", view=delete_user, name="delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", include("comhub.file_sharing_app.urls")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("comhub.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

comhub/file_sharing_app/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
# Create your models here.
User = get_user_model()

class File(models.Model):
    title = models.CharField(_("Title for the File"), max_length=50, null=True, blank=True)
    uploader = models.ForeignKey(User, verbose_name=_("uploader"), related_name="uploader", on_delete=models.CASCADE) 
    assigned_to = models.ForeignKey(User, verbose_name=_("assigned_to"), related_name="assigned_to", on_delete=models.CASCADE, null=True, blank=True )
    uploaded_file = models.FileField(_("File"), upload_to='uploads')
    note = models.TextField(_("Note or Reminder"), null=True, blank=True)


    def __str__(self):
        return self.title

    
    

comhub/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, TextField
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from model_utils.fields import StatusField
from model_utils import Choices
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    """
    Default custom user model for comhub.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    address = TextField(_("Address"), blank=True)
    phone_number = PhoneNumberField(_("User's Phone Number"), blank=True)
    user_type_choices = Choices('Admin','Suplier','Customer',)
    user_type = StatusField(choices_name='user_type_choices')
    customer_of = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)

    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

comhub/file_sharing_app/forms.py
import uuid
from allauth.account.forms import SignupForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from file_sharing_app.models import File

User = get_user_model()

class CustomerForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'username')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        password = str(uuid.uuid1()).split("-")[-1]
        self.fields['password1'].widget.attrs.update({'value':password})
        self.fields['password2'].widget.attrs.update({'value':password})

class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ('title','uploaded_file','note',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['note'].widget.attrs.update({'rows':3})

comhub/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

comhub/file_sharing_app/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from file_sharing_app.models import File
from .forms import CustomerForm, FileForm
# Create your views here.
User = get_user_model()


@login_required
def home(request):
    if request.user.user_type == "Customer":
        return redirect(customer_file_page, username=request.user.username)
    initial = {'email':  '@gmail.com'}
    form = CustomerForm(request.POST or None, initial=initial)
    if form.is_valid():
        customer_object = form.save(commit=False)
        customer_object.user_type = 'Customer'
        customer_object.customer_of = request.user
        customer_object.save()
        form = CustomerForm(initial=initial)
    context = {"form": form}
    return render(request, 'pages/home.html', context)


@login_required
def update_user(request, username):
    user = User.objects.filter(username=username, customer_of=request.user).first()
    form = CustomerForm(request.POST or None, instance=user)
    if form.is_valid():
        customer_object = form.save(commit=False)
        customer_object.user_type = 'Customer'
        customer_object.customer_of = request.user
        customer_object.save()
        return redirect("home")
    context = {"form": form}
    return render(request, 'pages/home.html', context)


@login_required
def about(request):
    return render(request, 'pages/about.html')


@login_required
def customer_file_page(request, username):
    customer = User.objects.filter(username=username).first()
    form = FileForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        file = form.save(commit=False)
        file.uploader = request.user
        file.assigned_to = customer
        file.save()
        form = FileForm()
    context = {
        "customer": customer,
        "form": form,
    }
    return render(request, 'pages/customer_file_page.html', context)


@login_required
def customer_file_upload_page(request, username, file_id):
    customer = User.objects.filter(username=username).first()
    file = File.objects.filter(id=file_id).first()
    form = FileForm(request.POST or None, request.FILES or None, instance=file or None)
    if form.is_valid():
        file = form.save(commit=False)
        file.uploader = request.user
        file.assigned_to = customer
        file.save()
        return redirect("customer_file_page", username=(customer.username))
    context = {
        "customer": customer,
        "form": form,
    }
    return render(request, 'pages/customer_file_page.html', context)

@login_required
def delete_file(request, file_id):
    file = File.objects.filter(id=file_id).first()
    file.delete()
    return redirect("customer_file_page", username=(file.assigned_to.username))

comhub/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from django.shortcuts import redirect
User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name", "address", "phone_number"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


@login_required
def delete_user(request, username):
    user = User.objects.filter(username=username, customer_of=request.user).first()
    user.delete()
    return redirect('home')
    

comhub/templates/pages/about.html
{% extends "base.html" %}

comhub/templates/pages/customer_file_page.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row mt-3">
    <div class="col-12 alert alert-warning text-center" role="alert">
        <h2>{% if customer.name %}{{customer.name}}{% else %}{{customer.username}}{% endif %}</h2>
    </div>
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-primary col-12 my-4">Submit</button>
        </form>
    </div>
    <div class="col-12">
        <div class="row">

        {% for file in customer.assigned_to.all %}
        <div class="col-6 my-3">
            <div class="card border-{% if file.uploader == request.user %}primary{% else %}danger{% endif %}">
                <div class="card-body">
                    <h4 class="card-title">{{file.title}}</h4>
                    <p class="card-text">{{file.note}}</p>
                    <a download href="{{file.uploaded_file.url}}" role="button" class="btn btn-primary">Download <i class="fas fa-download   fa-fw"></i></a>
                    {% if file.uploader == request.user %}
                    <a role="button" href="{% url 'customer_file_upload_page' customer.username file.id %}" class="btn btn-warning">Edit <i class="fas fa-edit   fa-fw"></i></a>
                    <a role="button" href="{% url 'delete_file' file.id %}" class="btn btn-danger">Delete <i class="fas fa-trash-alt   fa-fw"></i></a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock content %}

comhub/templates/pages/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-12 alert alert-primary text-center">
        <h1>
            {{request.user.name|title}}'s Customer
        </h1>
    </div>
    <div class="col-md-6">
        <div class="col-12 alert alert-danger text-center">
            <h3>
                Add Customer
            </h3>
        </div>
        <form action="." method="post">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-info m-2 p-2 col-3" type="submit">Submit</button>
        </form>
    </div>
    <div class="col-md-6">
        <div class="col-12 alert alert-danger text-center">
            <h3>
                All Customer
            </h3>
        </div>
        <div class="col-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Customer Name</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for customer in request.user.user_set.all %}
                    <tr>
                        <td scope="row">{{forloop.counter}}</td>
                        <td><a href="{% url 'customer_file_page' customer.username %}">{% if customer.name %}{{customer.name}}{% else %}{{customer.username}}{% endif %}</a></td>
                        <td>
                            <a class="btn btn-warning" href="{% url 'update_user' customer.username %}" role="button"><i class="fas fa-edit  fa-lg fa-fw"></i></a>
                            <a class="btn btn-danger" href="{% url 'users:delete' customer.username %}" role="button"><i class="fas fa-trash-alt fa-lg fa-fw"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
        </div>
    </div>
</div>
{% endblock content %}